name: Build and Publish

# Run this workflow every time a new commit pushed to your repository
on: push

jobs:
  # Set the job key. The key is displayed as the job name
  # when a job name is not provided
  catplist-build:
    # Name the Job
    name: Build catplist and publish
    # Set the type of machine to run on
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup python
        uses: actions/setup-python@v3

      - name: Install build and test dependencies
        run: python -m pip install --user --upgrade build setuptools wheel pytest pytest-cov click ruamel.yaml

      - name: Run small tests
        run: python -m pytest

      - name: Build
        run: python -m build

      - name: Publish package to TestPyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          repository_url: https://test.pypi.org/legacy/
          skip_existing: true

      - name: Test install
        run: python -m pip install --user --upgrade -i https://test.pypi.org/simple/ catplist

      - name: Publish package
        if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags')
        uses: pypa/gh-action-pypi-publish@release/v1
